TECH_HELP = {
    "RSI (14)": "Relative Strength Index using a 14-period Wilder calculation. Above 70 is often extended; below 30 is often oversold.",
    "Trend (EMA)": "Compares short and long exponential moving averages to identify the current trend bias.",
    "Sentiment": "Momentum label based on MACD versus signal line and RSI above or below 50.",
    "EMA 20": "Short-term exponential moving average. Often used as dynamic support/resistance for active trends.",
    "EMA 50": "Medium-term exponential moving average. Often used to judge institutional trend support.",
    "EMA 100": "Longer-term exponential moving average. Helps separate short pullbacks from deeper trend weakness.",
    "EMA 200": "Long-term exponential moving average. Widely watched as the dividing line between a primary uptrend and downtrend.",
    "Market Cap": "Company equity value calculated as share price times shares outstanding.",
    "Forward P/E": "Expected price-to-earnings ratio based on forward earnings estimates.",
    "PEG": "P/E adjusted for expected growth. Lower can imply cheaper growth, but estimates can be unreliable.",
    "Revenue Growth": "Most recent reported revenue growth rate from Yahoo Finance fundamentals.",
    "Debt/Equity": "Leverage ratio comparing total debt to shareholder equity.",
    "Relative Strength": "Stock return minus benchmark return over the selected window. Positive means the stock outperformed.",
    "Regime": "Broad market condition based on SPY and QQQ trading above or below their EMA200.",
    "SPY vs EMA200": "Percent distance of SPY from its 200-day exponential moving average.",
    "QQQ vs EMA200": "Percent distance of QQQ from its 200-day exponential moving average.",
    "VIX": "CBOE volatility index. Higher values generally indicate higher market stress.",
    "Suggested Entry": "Current price adjusted by the stock's average 20-day intraday drawdown from open to low.",
    "Stop": "Risk-control level set 8% below the suggested entry.",
    "Target": "Uses 20-day resistance when above entry; otherwise falls back to a 2R target.",
    "Reward/Risk": "Potential reward divided by risk per share. Values above 2R are generally more attractive.",
    "Backtest Entries": "Historical non-Avoid signals found using the current rules.",
    "20D Win Rate": "Percentage of historical signals with a positive 20-trading-day return.",
    "Avg 20D Return": "Average 20-trading-day return after historical non-Avoid signals.",
    "Worst 20D Adverse": "Worst low-to-entry move during the 20 trading days after historical signals.",
    "20D Drawdown": "Current close compared with the highest high in the last 20 trading days.",
    "20D Drawup": "Current close compared with the lowest low in the last 20 trading days.",
    "Drawdown >= 8%": "Core entry rule: price has pulled back at least 8% from the 10-day high.",
    "Within +/-6% EMA20": "Core entry rule: price is not too stretched from EMA20.",
    "RSI 42-58": "Core entry rule: RSI is in a neutral reset zone, not overbought or deeply weak.",
    "Vol Ratio >= 1.6x": "Core entry rule: latest volume is at least 1.6 times the recent 20-day average.",
    "MACD > Signal": "Momentum rule: MACD line is above its signal line.",
    "Above EMA50": "Supporting trend rule: price is above the medium-term EMA.",
    "78%-94% of 52W High": "Supporting relative-position rule: stock is below its high but not deeply broken.",
    "Above EMA100": "Supporting trend rule: price remains above the longer-term EMA100.",
    "ADX > 20": "Supporting trend-strength rule: ADX above 20 suggests a more defined trend.",
    "Above BB Middle": "Supporting volatility rule: price is above the Bollinger middle band.",
    "Stoch RSI < 75": "Supporting momentum rule: stochastic RSI is not too extended.",
    "Price below EMA 20": "Exit rule: close below EMA20 can indicate a short-term trend break.",
    "MACD Bearish Crossover": "Exit rule: MACD below signal suggests momentum deterioration.",
    "RSI Overbought": "Exit rule: RSI above 70 can signal an extended move vulnerable to reversal.",
    "Price at Upper Bollinger Band": "Exit rule: price at the upper band can indicate volatility extension.",
    "Price near 20D Resistance": "Exit rule: price is within 2% of the 20-day resistance level.",
}
